name: Mini Grafik Botu

on:
  workflow_dispatch:

concurrency:
  group: mini-grafik-botu
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Repo çek
        uses: actions/checkout@v4

      - name: Node kur
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Paketleri yükle
        run: npm install

      - name: Botu çalıştır
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node chart-bot.js