name: Tbulls Mini Chart Bot

on:
  workflow_dispatch:

concurrency:
  group: tbulls-mini-chart-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo indir
        uses: actions/checkout@v4

      - name: Node kur
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Paketleri kur
        run: npm install

      - name: Test
        run: node test.js
